version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: draw_app
    ports:
      - "5433:5432"
    volumes:
      - draw_app_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
 draw_app_data:
 redis_data:
